### ISSUE TITLE
pAkku, pGrid, pPv sensors shown as "unavailable"

### ISSUE THREAD

**Issue by parkflyer** [syssi/homeassistant-goecharger-mqtt#126]
I have added this automation:
```
alias: go-e Surplus Charging
description: >-
  Simple automation to update values needed for using solar surplus with go-e
  Chargers
trigger:
  - platform: time_pattern
    seconds: /5
condition: []
action:
  - service: mqtt.publish
    data:
      qos: "0"
      topic: go-eCharger/<go-e ID>/ids/set
      payload: >-
        {"pGrid":{{states("sensor.amis_power_saldo_w")}},"pPv":{{states("sensor.deye_modbus_sun12k_battery_output_power")}},"pAkku":
        0}
      retain: false
```
Then I wanted to check if everything is working correctly. But the sensors pAkku, pGrid and pPv are shown as "unavailable" ("nicht verfügbar"). 
![grafik](https://github.com/syssi/homeassistant-goecharger-mqtt/assets/143322799/44f986cf-684b-4688-9188-9832ccf8efeb)
Connection is generally OK and most sensors show data ("Charging energy limit" e.g. is also deactivated), fup is set to true and lmo to "Eco mode".
Currently the grid saldo is positive (buying energy, no surplus) and the car is not connected. Could this be the problem?

Thank you,
parkflyer
