### ISSUE TITLE
Entities not populating - what are correct settings?

### ISSUE THREAD

**Issue by jasunen** [syssi/homeassistant-goecharger-mqtt#130]
I have go-e Charger running and sending data to my MQTT server.
- In go-e app I have mqtt prefix = /goe/
- MQTT server is using authentication (username, password).

Home assistant has MQTT integration active and it works.
- I can listen /goe/# with Home Assistant MQTT integration and all go-e charger messages are received.

I enable your integration, have correct serial number and put /goe/ as topic.
Still entities are not populated and integration is not receiving any data.

What is correct way to setup the integration? There seems to be no clear instructions.

Edit: Charger is "**Go-e Charger Gemini**"

**Comment by syssi** [comment]
Could you provide some complete topic examples? Is there a serial number part of the topic? This is important.

**Comment by jasunen** [comment]
No, I am using bare **/goe/** as prefix in the e-go APP. 
In HA MQTT integration I receive following:

```
Message 172 received on /goe/rssi at 8:55 PM:
-78
QoS: 0 - Retain: false
Message 171 received on /goe/eto at 8:55 PM:
3932605
QoS: 0 - Retain: false
Message 170 received on /goe/tpa at 8:55 PM:
6462.143066
QoS: 0 - Retain: false
```

When configuring the go-eCharger (MQTT) integration:
```
Serial number*
123456

Base topic*
/goe/
```

I can also manually create MQTT sensors in HA configuration.yaml, i.e.
```
mqtt:
  sensor:
    - name: "goe_charger_eto_energy_total"
      state_topic: "/goe/eto"
    - name: "goe_charger_lmo_logic_mode"
      state_topic: "/goe/lmo"
```
And they work just fine!

HA version 2023.10.0
