### ISSUE TITLE
Services not working in current release (0.24.x)

### ISSUE THREAD

**Issue by 4homeassistant** [syssi/homeassistant-goecharger-mqtt#159]
For some reason the services in the current release seemed to stop working. I just went back to version 0.23 and it is working again but cannot say if it happend with 0.24 or 0.24.1 since I upgraded directly from 0.23 to 0.24.1.
Can someone confirm or refute this behaviour? Just saw that there has been a change in 0.24 https://github.com/syssi/homeassistant-goecharger-mqtt/pull/128 that may cause the issue but am no expert.
We've got two different go-e chargers: a Home Fix 11 kW from 2022 and a Gemini Fix 11 kW from 2023 and am on the current HA release and had the issue on both chargers.

**Comment by syssi** [comment]
Could you describe the issue in detail? Aren't the sensors updated anymore or are service calls broken?

**Comment by 4homeassistant** [comment]
Thank you @syssi, only the service calls are broken. Everything else is fine. I've got a couple of automations and templates based on services calls that didn't work anymore after updating and also doublechecked with the developer tools.

**Comment by 4homeassistant** [comment]
I also downgraded the chargers firmware to the last known working version (56.1). Can you see that behaviour in your environment?

**Comment by jusii** [comment]
Same happaned to me, downgraded back to 0.23

Also have made load balancing like this, and it no longer works 0.24+

```
service: goecharger_mqtt.set_config_key
data:
  serial_number: 201199
  key: amp
  value: "{{ (states.number.go_echarger_201199_amp.state |float|round(0) - 1)}}"

```
