### ISSUE TITLE
Add simple start/stop charging switch

### ISSUE THREAD

**Issue by kolossboss** [syssi/homeassistant-goecharger-mqtt#28]
Hi,

In the other custom goe-charger integration there is a switch to turn on/off allow charging.
In your integration I can do this by select `force-state =2` (1=stopped, not sure what 0 does)
It would be nice to simply have a switch to start/stop charging. Makes things much easier.

Thanks a lot :-)

**Comment by syssi** [comment]
There are some internal automations to start charging (f.e. if the price is low) and to stop charging (if an amount of energy is reached). The force state can be used to override these decision by `force on` or `force off`. Neutral (`0`) means no override.

It's hard to map these three states into one switch. Let's say we call the switch `switch.start_charging`. If this switcch is turned on the state `2` will be written. Which value should be written if we turn the switch off again? `1` would block all internal automations.

**Comment by syssi** [comment]
My go-e isn't installed yet. So may be you can answer some easy questions about the handling:

If we provide a `button.start_charging` entity similar to the `restart` button. Could also be done via a lovelace button card already:

```
type: button
name: Start charging
show_state: false
tap_action:
  action: call-service
  service: select.select_option
  target:
    entity_id: select.go_echarger_072246_frc
  data:
    option: '2'
```

The charging starts if you press this button. What do you do if you want to drive away and the charging isn't finished yet?
