### ISSUE TITLE
trx not available

### ISSUE THREAD

**Issue by 4homeassistant** [syssi/homeassistant-goecharger-mqtt#68]
I am trying to set the transaction id (trx) which basically works with any MQTT client but it isn't available in the UI. Tried to do in in YAML but it didn't work. Any suggestions what I can do?

**Comment by syssi** [comment]
The `trx` value is available as sensor only at the moment. Could you provide some examples values which can be passed to the `trx` topic? As workaround you could use the `goecharger_mqtt.set_config_key` service to the any values on any topic: https://github.com/syssi/homeassistant-goecharger-mqtt/#service-goecharger_mqttset_config_key

**Comment by 4homeassistant** [comment]
Thank you for your quick reply @syssi! 😊
Tried to do it with that script and already played around with the syntax but nothing happened. 
```
sequence:
  - service: goecharger_mqtt.set_config_key
    data:
      serial_number: "xxxxxx"
      key: "trx"
      value: "2"
```

**Comment by 4homeassistant** [comment]
Due to the api documentation https://github.com/goecharger/go-eCharger-API-v2/blob/main/apikeys-en.md you can pass the following values:
```
null: no ID set
0: charging without ID
1-10: charging with ID
```

**Comment by syssi** [comment]
I did the same using the `services` tab of the developer tools: http://your-homeassistant-host:8122/developer-tools/service

```
service: goecharger_mqtt.set_config_key
data:
  serial_number: "072246"
  key: trx
  value: 2
```

If I monitor the MQTT traffic using `mosquitto_sub -v -t '/go-eCharger/#'` I can see something like this:

```
$ mosquitto_sub -v -t '/go-eCharger/#'
/go-eCharger/072246/trx/set 1
/go-eCharger/072246/trx/result starting transaction for 1 is not allowed 1
```
