### ISSUE TITLE
Start / stop charging

### ISSUE THREAD

**Issue by woopstar** [syssi/homeassistant-goecharger-mqtt#73]
I installed this integration, and it works pretty smoothly out of the box. The only thing I need help finding is a simple button/switch to start/stop charging.

Am I understanding it correctly that I need to enable `frc` buttons? And if so, how do I do that?

**Comment by syssi** [comment]
Did you see this issue? https://github.com/syssi/homeassistant-goecharger-mqtt/issues/28

**Comment by woopstar** [comment]
> Did you see this issue? #28

Not at all. Thanks.

What is the diff between force off and neutral ?

**Comment by syssi** [comment]
The meaning of "neutral" is something like "charging allowed in general". Charging on and off overrides this default/neutral state.

**Comment by woopstar** [comment]
ah ok... so something like this would make a template switch to start/stop charging:

```
switch:
  - platform: template
    switches:
      goe_allow_charging:
        friendly_name: "Skylight"
        unique_id: goe_allow_charging
        value_template: "{{ is_state('sensor.go_echarger_222819_frc', 'Charge') }}"
        turn_on:
          service: select.select_option
          target:
            entity_id: select.go_echarger_072246_frc
          data:
            option: "2"
        turn_off:
          service: select.select_option
          target:
            entity_id: select.go_echarger_072246_frc
          data:
            option: "1"
        icon_template: >-
          {% if is_state('sensor.go_echarger_222819_frc', 'Charge') %}
            mdi:power-plug
          {% else %}
            mdi:power-plug-off
          {% endif %}
```
